# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :beta do
  increment_build_number(
    build_number: latest_testflight_build_number + 1,
    xcodeproj: "TTCheck.xcodeproj")
  build_app(scheme: "TTCheck")
  ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "mqhp-aaph-egvw-mhqd"
  ENV["PILOT_USERNAME"] = "juanpablo.ghelfi@gmail.com"
  upload_to_testflight(skip_waiting_for_build_processing: true)
end
